"""initial migrate

Revision ID: 07023c6b175a
Revises: 
Create Date: 2024-08-03 21:45:47.351613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07023c6b175a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristicas', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('pantalla',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('camara',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('cpu',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('caracteristicas', schema=None) as batch_op:
        batch_op.alter_column('cpu',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('camara',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('pantalla',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
